// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentSystem.Database;

#nullable disable

namespace StudentSystem.Migrations
{
    [DbContext(typeof(StudentSystemDbContext))]
    partial class StudentSystemDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StudentSystem.Database.Entitties.Department", b =>
                {
                    b.Property<string>("DepartmentCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DepartmentCode");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DepartmentCode = "CS1234",
                            DepartmentName = "ComputerScience"
                        },
                        new
                        {
                            DepartmentCode = "MTH567",
                            DepartmentName = "Mathematics"
                        });
                });

            modelBuilder.Entity("StudentSystem.Database.Entitties.DepartmentLectures", b =>
                {
                    b.Property<string>("DepartmentCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LectureName")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("DepartmentCode", "LectureName");

                    b.HasIndex("LectureName");

                    b.ToTable("DepartmentLectures");

                    b.HasData(
                        new
                        {
                            DepartmentCode = "CS1234",
                            LectureName = "Algorithms"
                        },
                        new
                        {
                            DepartmentCode = "CS1234",
                            LectureName = "DataStructures"
                        },
                        new
                        {
                            DepartmentCode = "MTH567",
                            LectureName = "Calculus"
                        });
                });

            modelBuilder.Entity("StudentSystem.Database.Entitties.Lecture", b =>
                {
                    b.Property<string>("LectureName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<TimeOnly>("LectureEndTime")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("LectureStartTime")
                        .HasColumnType("time");

                    b.HasKey("LectureName");

                    b.ToTable("Lectures");

                    b.HasData(
                        new
                        {
                            LectureName = "Algorithms",
                            LectureEndTime = new TimeOnly(11, 30, 0),
                            LectureStartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            LectureName = "Calculus",
                            LectureEndTime = new TimeOnly(13, 30, 0),
                            LectureStartTime = new TimeOnly(12, 0, 0)
                        },
                        new
                        {
                            LectureName = "DataStructures",
                            LectureEndTime = new TimeOnly(15, 30, 0),
                            LectureStartTime = new TimeOnly(14, 0, 0)
                        });
                });

            modelBuilder.Entity("StudentSystem.Database.Entitties.Student", b =>
                {
                    b.Property<int>("StudentNumber")
                        .HasColumnType("int");

                    b.Property<string>("DepartmentCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentNumber");

                    b.HasIndex("DepartmentCode");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentNumber = 12345678,
                            DepartmentCode = "CS1234",
                            Email = "john.smith@example.com",
                            FirstName = "John",
                            LastName = "Smith"
                        },
                        new
                        {
                            StudentNumber = 87654321,
                            DepartmentCode = "MTH567",
                            Email = "alice.johnson@example.com",
                            FirstName = "Alice",
                            LastName = "Johnson"
                        });
                });

            modelBuilder.Entity("StudentSystem.Database.Entitties.StudentLecture", b =>
                {
                    b.Property<string>("LectureName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("StudentNumber")
                        .HasColumnType("int");

                    b.HasKey("LectureName", "StudentNumber");

                    b.HasIndex("StudentNumber");

                    b.ToTable("StudentLecture");

                    b.HasData(
                        new
                        {
                            LectureName = "Algorithms",
                            StudentNumber = 12345678
                        },
                        new
                        {
                            LectureName = "DataStructures",
                            StudentNumber = 12345678
                        },
                        new
                        {
                            LectureName = "Calculus",
                            StudentNumber = 87654321
                        });
                });

            modelBuilder.Entity("StudentSystem.Database.Entitties.DepartmentLectures", b =>
                {
                    b.HasOne("StudentSystem.Database.Entitties.Department", null)
                        .WithMany()
                        .HasForeignKey("DepartmentCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentSystem.Database.Entitties.Lecture", null)
                        .WithMany()
                        .HasForeignKey("LectureName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StudentSystem.Database.Entitties.Student", b =>
                {
                    b.HasOne("StudentSystem.Database.Entitties.Department", "Department")
                        .WithMany("Students")
                        .HasForeignKey("DepartmentCode");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("StudentSystem.Database.Entitties.StudentLecture", b =>
                {
                    b.HasOne("StudentSystem.Database.Entitties.Lecture", null)
                        .WithMany()
                        .HasForeignKey("LectureName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentSystem.Database.Entitties.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StudentSystem.Database.Entitties.Department", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
